openapi: 3.0.4
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: This is a sample
  version: 1.0.12
paths:
  /test/{test_id}:
    get:
      parameters:
        - name: test_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestSchema'

components:
  schemas:
    TestSchema:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
  requestBodies:
