/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../../pages/__root'
import { Route as IndexImport } from './../../pages/index'
import { Route as TaskIndexImport } from './../../pages/task/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TaskIndexRoute = TaskIndexImport.update({
  id: '/task/',
  path: '/task/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/task/': {
      id: '/task/'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/task': typeof TaskIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/task': typeof TaskIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/task/': typeof TaskIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/task'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/task'
  id: '__root__' | '/' | '/task/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaskIndexRoute: typeof TaskIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaskIndexRoute: TaskIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/task/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/task/": {
      "filePath": "task/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
